name:                aoc2020
version:             0.5.0
github:              "blmage/aoc2020"
license:             MIT
author:              "Benoît Leulliette"
maintainer:          "benoit.leulliette@gmail.com"
copyright:           "2020 Benoît Leulliette"

extra-source-files:
- README.md

description:         Solutions to Advent of Code 2020.

dependencies:
- base-noprelude >= 4.7 && < 5
- cond
- constraints
- containers
- finite-typelits
- groupBy
- megaparsec
- microlens
- monad-control
- mtl
- parsers
- parsers-megaparsec
- relude
- singletons
- singletons-dict-getter
- split
- streaming
- string-interpolate
- transformers
- typerep-map
- vector-sized
- void

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020

tests:
  aoc2020-doctest:
    main: Doctest.hs
    source-dirs:
    - test
    dependencies:
    - aoc2020
    - doctest
    - doctest-discover-hpack