name:                aoc2020
version:             0.1.0
github:              "blmage/aoc2020"
author:              "blmage"

extra-source-files:
- README.md

description:         Solutions to Advent of Code 2020.

dependencies:
- base-noprelude >= 4.7 && < 5
- constraints
- megaparsec
- monad-control
- mtl
- parsers
- parsers-megaparsec
- relude
- singletons
- streaming
- transformers
- void

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020

tests:
  aoc2020-doctest:
    main: Doctest.hs
    source-dirs:
    - test
    dependencies:
    - aoc2020
    - doctest
    - doctest-discover-hpack